version: '3'

services:
  back:
    image: qubis/taiga-back
    container_name: taiga-back
    restart: unless-stopped
    depends_on:
      - db
      - events
    networks:
      - default
    volumes:
      - ${DOCKER_DATA_DIR}/taiga/media:/taiga-media
      - ${DOCKER_DATA_DIR}/taiga/conf/back:/taiga-conf
    env_file:
      - variables.env

  front:
    image: qubis/taiga-front
    container_name: taiga-front
    restart: unless-stopped
    networks:
      - default
    volumes:
      - ${DOCKER_DATA_DIR}/taiga/conf/front:/taiga-conf
    env_file:
      - variables.env

  db:
    image: postgres:11-alpine
    container_name: taiga-db
    restart: unless-stopped
    networks:
      - default
    env_file:
      - variables.env
    volumes:
      - ${DOCKER_DATA_DIR}/taiga/db:/var/lib/postgresql/data

  rabbit:
    image: qubis/taiga-rabbit
    container_name: taiga-rabbit
    restart: unless-stopped
    networks:
      - default
    env_file:
      - variables.env

  events:
    image: qubis/taiga-events
    container_name: taiga-events
    restart: unless-stopped
    depends_on:
      - rabbit
    networks:
      - default
    env_file:
      - variables.env

  proxy:
    image: qubis/taiga-proxy
    container_name: taiga-proxy
    restart: unless-stopped
    depends_on:
      - back
      - front
      - events
    networks:
      - default
    ports:
      - 9180:80
      - 9443:443
    volumes:
      #- ${DOCKER_DATA_DIR}/taiga/cert:/taiga-cert
      - ${DOCKER_DATA_DIR}/taiga/conf/proxy:/taiga-conf
    env_file:
      - variables.env

networks:
  default:
